### ISSUE TITLE
无法上传数据集

### ISSUE THREAD

**Issue by lee1906068** [LibCity/Bigscity-LibCity-WebTool#1]
管理平台部署完成，可在客户端登录，但是无法上传数据集文件，可以下载样例数据。
上传文件提交后，进度条走完后没有反应，数据集列表也没有变化。不知道是否配置文件没有配置正确，希望能给予指导，谢谢！
![捕获](https://user-images.githubusercontent.com/58378019/187033327-aade2ca0-94b0-4f5d-8adc-db10f5c65882.PNG)

`ALLOWED_HOSTS = ['192.168.xx.xx']
#- 数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django',  # 指定的数据库名
        'USER': 'root',  # 数据库登录的用户名
        'PASSWORD': '123456',  # 登录数据库的密码
        'HOST': '0.0.0.0',
        'PORT': '3306',
    }
}

#- 跨域设置
#- 单个配置
CORS_ORIGIN_WHITELIST = (
    'http://0.0.0.0:8000',
)

#- 允许携带cookie
CORS_ALLOW_CREDENTIALS = True

#- 允许所有主机跨域
CORS_ORIGIN_ALLOW_ALL = True

#- libcity库程序相关
#- libcity程序目录
LIBCITY_PATH = '/home/lee/Bigscity-LibCity-WebTool/Bigscity-LibCity'
#- 指标文件目录
EVALUATE_PATH_PREFIX = LIBCITY_PATH + os.sep +'libcity' + os.sep + 'cache' + os.sep
EVALUATE_PATH_SUFFIX = os.sep + 'evaluate_cache' + os.sep
#- run_model.py脚本文件位置
RUN_MODEL_PATH = 'run_model.py'
#- 激活libcity库虚拟环境命令
ACTIVE_VENV = None
#- libcity的log目录
LOG_PATH = LIBCITY_PATH + os.sep + 'libcity' + os.sep + 'log' + os.sep
#- libcity的 任务-模型 对应关系配置信息目录
TASK_MODEL_PATH = LIBCITY_PATH + os.sep + 'libcity' + os.sep + 'config' + os.sep + 'model'

#- 数据集文件上传路径
DATASET_PATH = LIBCITY_PATH + os.sep + 'raw_data' + os.sep

#- 任务参数json文件上传路径
TASK_PARAM_PATH = LIBCITY_PATH + os.sep

#- 样例文件相关
#- 数据集样例文件
DATASET_EXAMPLE_PATH = '/home/lee/Bigscity-LibCity-WebTool/smartcityms_backend/sample/T_DRIVE_SMALL.zip'
TASK_PARAM_EXAMPLE_PATH = '/home/lee/Bigscity-LibCity-WebTool/smartcityms_backend/sample/config.json'
ADMIN_FRONT_HTML_PATH = '/home/lee/Bigscity-LibCity-WebTool/smartcityms_front/dist/'`

**Comment by hybridIce** [comment]
你好，请问你知道在注册账号界面出现代号为500的错误是什么原因么？

**Comment by charleshuangruo** [comment]
> 管理平台部署完成，可在客户端登录，但是无法上传数据集文件，可以下载样例数据。 上传文件提交后，进度条走完后没有反应，数据集列表也没有变化。不知道是否配置文件没有配置正确，希望能给予指导，谢谢！ ![捕获](https://user-images.githubusercontent.com/58378019/187033327-aade2ca0-94b0-4f5d-8adc-db10f5c65882.PNG)
> 
> `ALLOWED_HOSTS = ['192.168.xx.xx'] #- 数据库 DATABASES = { 'default': { 'ENGINE': 'django.db.backends.mysql', 'NAME': 'django', # 指定的数据库名 'USER': 'root', # 数据库登录的用户名 'PASSWORD': '123456', # 登录数据库的密码 'HOST': '0.0.0.0', 'PORT': '3306', } }
> 
> #- 跨域设置 #- 单个配置 CORS_ORIGIN_WHITELIST = ( 'http://0.0.0.0:8000', )
> 
> #- 允许携带cookie CORS_ALLOW_CREDENTIALS = True
> 
> #- 允许所有主机跨域 CORS_ORIGIN_ALLOW_ALL = True
> 
> #- libcity库程序相关 #- libcity程序目录 LIBCITY_PATH = '/home/lee/Bigscity-LibCity-WebTool/Bigscity-LibCity' #- 指标文件目录 EVALUATE_PATH_PREFIX = LIBCITY_PATH + os.sep +'libcity' + os.sep + 'cache' + os.sep EVALUATE_PATH_SUFFIX = os.sep + 'evaluate_cache' + os.sep #- run_model.py脚本文件位置 RUN_MODEL_PATH = 'run_model.py' #- 激活libcity库虚拟环境命令 ACTIVE_VENV = None #- libcity的log目录 LOG_PATH = LIBCITY_PATH + os.sep + 'libcity' + os.sep + 'log' + os.sep #- libcity的 任务-模型 对应关系配置信息目录 TASK_MODEL_PATH = LIBCITY_PATH + os.sep + 'libcity' + os.sep + 'config' + os.sep + 'model'
> 
> #- 数据集文件上传路径 DATASET_PATH = LIBCITY_PATH + os.sep + 'raw_data' + os.sep
> 
> #- 任务参数json文件上传路径 TASK_PARAM_PATH = LIBCITY_PATH + os.sep
> 
> #- 样例文件相关 #- 数据集样例文件 DATASET_EXAMPLE_PATH = '/home/lee/Bigscity-LibCity-WebTool/smartcityms_backend/sample/T_DRIVE_SMALL.zip' TASK_PARAM_EXAMPLE_PATH = '/home/lee/Bigscity-LibCity-WebTool/smartcityms_backend/sample/config.json' ADMIN_FRONT_HTML_PATH = '/home/lee/Bigscity-LibCity-WebTool/smartcityms_front/dist/'`

看一下最新更新的部署手册（uwsgi或waitress），前后端ip是否填写正确；然后不要忘记在Nginx的“mysite.conf”文件开头添加“client_max_body_size 20000m;”语句，涉及附件大小的声明，否则不会真正上传。

**Comment by charleshuangruo** [comment]
> 你好，请问你知道在注册账号界面出现代号为500的错误是什么原因么？

应该是没有正确连接后端。看一下最新更新的部署手册（uwsgi或waitress），检查前后端ip是否填写正确。
